apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextjs-app
  template:
    metadata:
      labels:
        app: my-nextjs-app
    spec:
      containers:
      - name: my-nextjs-app
        image: mynextjsapp.azurecr.io/my-nextjs-app:v1
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-secret
